#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys

import torch

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from llm_das_dinomaly.enhancer import MapFeatureHead, build_enhancer_features
from llm_das_dinomaly.enhancer.heads import binary_enhancer_loss
from llm_das_dinomaly.utils import seed_everything


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Run one optimizer step on synthetic tensors.")
    parser.add_argument("--cache", type=Path, help="Hard sample cache generated by the server pipeline.")
    parser.add_argument("--output", type=Path, default=Path("outputs/enhancer.pt"))
    parser.add_argument("--seed", type=int, default=7)
    args = parser.parse_args()

    if args.cache is not None and not args.dry_run:
        from llm_das_dinomaly.pipelines.server_mvtec import train_enhancer_from_cache

        summary = train_enhancer_from_cache(args.cache, args.output, epochs=1, hidden_dim=128, lr=1e-3, seed=args.seed)
        print(summary)
        return

    if not args.dry_run:
        raise SystemExit("Use --dry-run for dummy mode, or --cache for real cached features.")

    generator = seed_everything(args.seed)
    base_score = torch.rand(8, generator=generator)
    anomaly_map = torch.rand(8, 1, 28, 28, generator=generator)
    feats = [torch.rand(8, 8, 4, 4, generator=generator), torch.rand(8, 8, 4, 4, generator=generator)]
    x = build_enhancer_features(base_score, anomaly_map, encoder_groups=feats)
    labels = torch.cat([torch.zeros(4), torch.ones(4)])
    head = MapFeatureHead(input_dim=x.shape[1], hidden_dim=16)
    opt = torch.optim.AdamW(head.parameters(), lr=1e-3)
    logits = head(x)
    loss = binary_enhancer_loss(logits, labels)
    loss.backward()
    opt.step()
    print(f"dry-run loss={loss.item():.6f}")


if __name__ == "__main__":
    main()
